services:
  - type: web
    name: motrix-python-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: web
    name: motrix-laravel-app
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan migrate --force && apache2-foreground
    envVars:
      - key: APP_KIND
        value: laravel
      - key: PYTHON_SERVICE_URL
        fromService:
          type: web
          name: motrix-python-api
          property: host
