services:
  - type: web
    name: motrix-python-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /productos
    envVars:
      - key: DB_HOST
        value: TU_HOST_MYSQL_EXTERNO
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: TU_USUARIO
      - key: DB_PASSWORD
        value: TU_PASSWORD
      - key: DB_NAME
        value: TU_DB
